--insert into PERSON (FIRSTNAME, LASTNAME)
--values ('Ron', 'Lewis')


select *
from PERSON;

INSERT INTO TRIP (NAME, COUNTRY, TRIP_DATE, NO_PLACES)
values ('Trip from past', 'Country1', TO_DATE('2021-03-01', 'YYYY-MM-DD'), 8);

INSERT INTO TRIP (NAME, COUNTRY, TRIP_DATE, NO_PLACES)
values ('Trip 1', 'Country2', TO_DATE('2021-03-20', 'YYYY-MM-DD'), 2);

INSERT INTO TRIP (NAME, COUNTRY, TRIP_DATE, NO_PLACES)
values ('Trip 2', 'Country3', TO_DATE('2021-03-25', 'YYYY-MM-DD'), 7);

INSERT INTO TRIP (NAME, COUNTRY, TRIP_DATE, NO_PLACES)
values ('Trip 3', 'Country4', TO_DATE('2021-04-20', 'YYYY-MM-DD'), 12);

INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (1, 2, 'P');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (1, 3, 'C');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (3, 1, 'P');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (3, 2, 'P');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (3, 4, 'C');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (3, 5, 'N');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (2, 10, 'N');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (4, 8, 'N');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (4, 9, 'C');
INSERT INTO RESERVATION (TRIP_ID, PERSON_ID, STATUS)
values (4, 3, 'P');

create view V_Reservations
as
    select
        COUNTRY, TRIP_DATE, NAME, FIRSTNAME, LASTNAME, RESERVATION_ID, STATUS
    from RESERVATION R
    join PERSON P on P.PERSON_ID = R.PERSON_ID
    join TRIP T on T.TRIP_ID = R.TRIP_ID



