create trigger RESERVATION_ADD_TRIGGER
	after insert
	on RESERVATION
	for each row
BEGIN
    INSERT INTO RESERVATION_LOG
        (RESERVATION_ID, CHANGE_DATE, STAUS)
    VALUES (:NEW.RESERVATION_ID, CURRENT_DATE, :NEW.STATUS);
    UPDATE TRIP
    SET TRIP.NO_AVAILABLE_PLACES = TRIP.NO_AVAILABLE_PLACES - 1
    WHERE TRIP.TRIP_ID = :NEW.TRIP_ID;
end;
/

